repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff check
        entry: uv run ruff check
        language: system
        pass_filenames: false
        always_run: true

      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false  # pytest doesn't need file names
        always_run: true

      - id: uv-sync
        name: uv sync
        entry: uv sync --all-extras --dev --locked
        language: system
        pass_filenames: false
        always_run: true